I was always a “child of the earth”, and had a strong connection to nature starting at a very young age. I wanted to be an entomologist for most of my life; I used to do thing like bring home cockroaches from school after rescuing them, and I would build them little houses outside. I have also always really liked plants. One of my earliest memories is being fascinated by David Attenborough's “Private Life of Plants”. This documentary prompted 6-year-old me to do a class project on epiphytic and parasitic plants where I found different examples of these plants and researched them, ultimately bringing it all into school to present. After a certain point, all of my elementary school projects revolved around plants. This all fed into my general love of science and biology, and I pursued these studies through high school. During that time, I discovered I really prefer applied sciences.

I started college as a fiber arts major, but my program was canceled during my first semester. I then switched to ecology and evolutionary biology, EEB, because I knew I liked science and biology. However, I was really unimpressed with the required courses and the lack of student involvement with the college. While I was taking the gen-ed class “Mushrooms, Molds, Man” with Dr. Pryor, he hired me to help him with his lab website more or less out of the blue. A week later, I got an interview with the College of Agriculture’s web development group (then only 2 people) after they heard I was helping Dr. Pryor. They hired me for a long term position where I would train in Drupal development.

Through my job I discovered the College of Agriculture, which seemed like they taught exactly what was missing from EEB. Real-world, hands-on applications were being taught, and there seemed to be a community of really great, involved people in the College. I decided to become a plant sciences major after my mother reminded me about what I did when I was much younger, and what she thought it was that I had been most interested in my whole life.

Once I found my college “home”, I began to take all the PLS courses I could, spending several years ignoring my gen-eds in favor of taking upper division classes I found to be interesting. I quickly moved from my job with Dr. Pryor to focus more on my web development job. I took a number of courses over at the CEAC, and spent a semester working in the Teaching Greenhouse growing tomatoes after I took both hydroponic production classes. I took Dr. Quist’s Asexual Propagation class and discovered I enjoyed plant anatomy and phylogeny a lot. I also took the Plant Physiology lab class. There, we made transgenic plants with a DNA construct containing a heat shock protein and a luciferase tag so the plants would fluoresce. The course required us to make the DNA construct, insert it into Agrobacterium, infect Arabidopsis embryos, grow them, and ultimately select the working transgenic plants from the seeds. This class was really a cool exposure to what a research job in plant science laboratory was like, but as a result I found myself more interested in horticulture than in the research side of things. Because of this experience, I decided I probably didn’t want to work in a research lab - I prefer to work in a broader environment than to take a extremely narrow focus on one tiny aspect of the much bigger picture.

Last July, I went abroad for a month to take a UA course in the Galapagos Islands that focused on introductory ecology field work. We were required to come up with a project idea, then to spend time over the trip recording data to analyse and report on at the end. I did two small projects, one on pollinator frequency & preferences, and one on lava lizard parasite loads. The trip was absolutely fantastic, and frequently I was called upon to help educate my colleagues about the plants we were around. I also was asked to TA for Dr. Mangin’s ECOL182 class after going on the trip with her. I believe this had a lot to do with my enthusiasm for the plants and animals I got to see on the islands, as well as my joy in sharing information I found interesting.

Working in a small team collecting field data was really enjoyable, and has inspired me to start volunteering with several projects. I have since helped with data collection on the native fish in Aravaipa Canyon, and helped trap ferrets for the Black-Footed Ferret Recovery Program in Northern Arizona. I intend to continue volunteering  with research teams in the field wherever I can. That way, I can both help those projects move along, as well as keep in touch with science and research without having to pick one specific topic to pursue.

My web development job has been a huge part of my life since my first year in college. They trained me to the point where I am now the primary Drupal developer for the College. Our unit has grown a lot since I was hired, and I have a very tight-knit group of colleagues I really enjoy working with. Because I have become so proficient in Drupal development, I want to try and build a career out of the job I have now. My background in sciences, especially plant science, has enabled me to branch out and begin contracting with researchers as a liaison between them and their websites. I already have a contract for the SPLS Department site, the Pollen RCN site, and the Palanivelu Lab site. This has allowed me to get involved and network with a variety of people. Currently I am working on being hired full time by the School of Plant Sciences so I can offer my services to more of the researchers here. I think there is real value in research having a web presence, and I want to help fill the void in that presence here at the UA. I intend to get my scientific illustration certification, and also want to also begin doing some science writing so I can help generate content for the sites I will be maintaining and working on.

I like learning for learning's sake. But unfortunately I have been struggling with motivation in graded classes because  I would just like to hear about cool things I didn’t already know. At this point in my life, I am definitely conflicted about my desire to continue learning in a structured environment after I graduate. I definitely want to continue my art education, which has been on hold for 4 years. Also, plant-insect-fungi interactions are fascinating, and I would love to learn more about how these ancient life forms affect each other and co-evolve. Ultimately, I will probably end up taking classes without necessarily trying to get another degree or going to graduate school.
